on:
    push:
        branches: main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
            - uses: JS-DevTools/npm-publish@v4
              with:
                  token: ${{ secrets.NPM_TOKEN }}
